fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        pass_filenames: false
        language: system

      - id: isort
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system

      - id: flake8
        name: flake8
        entry: poetry run flake8p .
        pass_filenames: false
        language: system

      - id: mypy
        name: mypy
        entry: poetry run mypy . --install-types --non-interactive
        pass_filenames: false
        language: system

      - id: pytest
        name: pytest
        entry: poetry run pytest --cov=src --cov-report=term-missing --cov-fail-under=80
        pass_filenames: false
        language: system
